# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    sensor.iio.enable = lib.mkDefault true;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking = {
    useDHCP = lib.mkDefault true;
    # interfaces = {
    #   tailscale0.useDHCP = lib.mkDefault true;
    #   virbr0.useDHCP     = lib.mkDefault true;
    #   virbr1.useDHCP     = lib.mkDefault true;
    #   wg-sea1.useDHCP    = lib.mkDefault true;
    #   wlan0.useDHCP      = lib.mkDefault true;
    #
    #   eth0.useDHCP       = lib.mkDefault false;
    #   wlp166s0.useDHCP   = lib.mkDefault true;
    #   enp0s13f0u2c2.useDHCP = lib.mkDefault true;
    # };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
